### ISSUE TITLE
Code block on mobile inconsistent

### ISSUE THREAD

**Issue by shilman** [storybookjs/frontpage#155]
![image](https://user-images.githubusercontent.com/488689/90095778-3db59580-dd64-11ea-8b8e-2a729709dd4a.png)

On the toolbars page. Lower down on the same page:

![image](https://user-images.githubusercontent.com/488689/90095756-2d9db600-dd64-11ea-93df-0d3c39dc8ed9.png)

**Comment by domyen** [comment]
Yes this is very strange indeed. I can reproduce this on my iPhone and in the iOS simulator at this link https://storybook.js.org/docs/react/essentials/toolbars-and-globals

@kylesuss is this something you can take a look at? Is this the CodeSnippets component?

**Comment by kylesuss** [comment]
Is the issue that the font sizes are different? If so, likely not the CodeSnippets component. Anyway, I will take a look but want to understand if it is something else in addition to the font size.

**Comment by domyen** [comment]
There's a font-size difference. 

I also don't see the commented out filenames at the beginning of the code snippets (e.g., `// .storybook/preview.js`).

| Mobile  | Desktop  |
|---|---|
| ![IMG_743B6B2F4902-1](https://user-images.githubusercontent.com/263385/90196194-3197fb00-dd99-11ea-865a-2c00ab04d91d.jpeg) | <img width="534" alt="Screen Shot 2020-08-13 at 7 12 08 PM" src="https://user-images.githubusercontent.com/263385/90196143-10cfa580-dd99-11ea-9da5-ff2e9376b3fa.png">  |

**Comment by kylesuss** [comment]
@domyen thanks that is helpful. You're right about it being (at least partially) an issue w/ the design system -- didn't expect that. I'll take a look at this early next week.

**Comment by kylesuss** [comment]
The text sizing issue was fixed. Still need to see what's up with the comments missing on iOS

**Comment by kylesuss** [comment]
@domyen I just got around to testing this on a real device. I see the comments:
![snippet](https://user-images.githubusercontent.com/3035355/95637742-b9278080-0a4f-11eb-9e69-c77e31b4f7e4.jpg)

Can you look into this since I can't reproduce the problem? I feel a bit limited in debugging here since both the simulator and the iPhone 11 I tried to test this seem to render the comments just fine.

**Comment by domyen** [comment]
I still don't see them. Let's get a sanity check from someone else. My iphone 11 could be wrong.

@shilman could you go to this url https://storybook.js.org/docs/react/get-started/setup on your iphone and check if you see code comments in the snippets?

![4A4D2727-5F88-42F8-8514-85AB0207B6E6_1_102_o](https://user-images.githubusercontent.com/263385/95885821-bbd5ee80-0d4b-11eb-83dd-2729c4144ddb.jpeg)

**Comment by shilman** [comment]
This is what i see @domyen 

![image](https://user-images.githubusercontent.com/488689/95886218-e1e1aa00-0db0-11eb-933e-50b40802ddf7.png)

**Comment by domyen** [comment]
Thanks for the quick reply @shilman. Looks like my phone is somehow bonked (lucky me). Closing this issue now. Thanks for sorting it out @kylesuss!
